version: '3.8'

services:

  backend:
    container_name: taskaura-api
    build:
      context: ./taskaura_backend  
    ports:
      - "8081:8081"             
    env_file:
      - ./taskaura_backend/.env  
    restart: unless-stopped

 

  frontend:
    container_name: taskaura-web
    build:
      context: ./taskaura_Frontend 
    ports:
      - "3000:80"              
    restart: unless-stopped
    depends_on:
      - backend               